# Generated by Django 5.0.7 on 2024-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('generation', models.CharField(max_length=3)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('drive', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('color', models.TextField()),
                ('horsePower', models.TextField()),
                ('run', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
